esphome:
  name: watermeter

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  #password: !secret decoder_OTA

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

external_components:
  - source: custom_components

spi:
  clk_pin: GPIO14
  miso_pin: GPIO12
  mosi_pin: GPIO13

sensor:
  - platform: xl4432_spi_sensor
    name: xl4432
    cs_pin: GPIO15
    meter_id: [0x4E, 0x61, 0xBC]  # Define your meter ID here

mqtt:
  broker: !secret Dialog3G_Decoder_BROKER
  username: !secret Dialog3G_Decoder_BROKER_USER
  password: !secret Dialog3G_Decoder_BROKER_PASS
    
